version: "3.8"
services:
  db:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cta
      POSTGRES_PASSWORD: cta
    volumes:
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "3000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: cta
      PGADMIN_DEFAULT_PASSWORD: cta
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json

  grafana:
    build: .
    image: grafana/grafana:7.5.7
    ports:
      - 3001:3000
    depends_on:
    - db
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
